name: MacOS X build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: |
        brew install libx11 libxi libxtst

    - name: configure
      run: ./configure

    - name: build
      run: make

    - name: stage install
      run: DESTDIR=spacenavd-macosx make install

    - uses: actions/upload-artifact@v4
      with:
        name: spacenavd-macosx
        path: spacenavd-macosx

  build-nox11:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure --disable-x11

    - name: build
      run: make

    - name: stage install
      run: DESTDIR=spacenavd-macosx-nox11 make install

    - uses: actions/upload-artifact@v4
      with:
        name: spacenavd-macosx-nox11
        path: spacenavd-macosx-nox11

# vi:ts=2 sts=2 sw=2 expandtab:
