name: GNU/Linux build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libx11-dev libxi-dev libxtst-dev

    - name: configure
      run: ./configure

    - name: build
      run: make

    - name: stage install
      run: DESTDIR=spacenavd-gnulinux make install

    - uses: actions/upload-artifact@v4
      with:
        name: spacenavd-gnulinux
        path: spacenavd-gnulinux

  build-nox11:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure --disable-x11

    - name: build
      run: make

    - name: stage install
      run: DESTDIR=spacenavd-gnulinux-nox11 make install

    - uses: actions/upload-artifact@v4
      with:
        name: spacenavd-gnulinux-nox11
        path: spacenavd-gnulinux-nox11


# vi:ts=2 sts=2 sw=2 expandtab:
